#!/usr/bin/env python3
"""Explore data-driven flood-risk street typologies with HDBSCAN."""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path
from typing import Optional

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


# This is an unsupervised clustering experiment.
# The goal is to examine whether street typologies naturally emerge from raw
# HEV indicators and to compare them with an existing rule-based framework.
# This is not supervised training: rule-based labels are never clustering inputs.
FLOOD_SCENARIO = "PF"  # Use "PF" for Permanent Flooding or "TF" for Temporary Flooding.
CONDA_ENVIRONMENT = "2026master"

SCRIPT_DIR = Path(__file__).resolve().parent
# Use the capped dataset generated by the cleaning script for clustering.
# To audit the uncapped intermediate dataset, set this to
# "MT_UPDATE_MS_HEV_cleaned.csv" or pass it through --input.
INPUT_FILENAME = "MT_UPDATE_MS_HEV_NORcleaned.csv"
INPUT_CSV = SCRIPT_DIR / "../data" / INPUT_FILENAME
OUTPUT_ROOT = SCRIPT_DIR / "../outputs_hdbscan"

ID_COLUMN_CANDIDATES = ("fid", "MS_ID")
RULE_LABEL_CANDIDATES = (
    "rule_type",
    "type_label",
    "typology",
    "intervention_type",
)
EXCLUDED_FEATURE_KEYWORDS = (
    "risk",
    "score_b1",
    "score_b2",
    "label",
    "intervention",
    "index",
    "result",
)
MIN_CLUSTER_SIZES = (50, 100, 200)
MIN_SAMPLES_VALUES = (10, 20, 40)
METRIC = "euclidean"
CLUSTER_SELECTION_METHOD = "eom"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run unsupervised HDBSCAN clustering for PF or TF indicators."
    )
    parser.add_argument(
        "--scenario",
        choices=("PF", "TF"),
        default=FLOOD_SCENARIO,
        help=f"Flood scenario to analyze (default: {FLOOD_SCENARIO}).",
    )
    parser.add_argument(
        "--input",
        type=Path,
        default=INPUT_CSV,
        help=f"Input CSV (default: {INPUT_CSV}).",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=OUTPUT_ROOT,
        help=f"Output root directory (default: {OUTPUT_ROOT}).",
    )
    parser.add_argument(
        "--audit-only",
        action="store_true",
        help="Prepare features and save audit files without running HDBSCAN.",
    )
    return parser.parse_args()


def check_conda_environment() -> None:
    """Warn when VSCode or the shell is not using the configured Conda environment."""
    active_environment = os.environ.get("CONDA_DEFAULT_ENV")
    if active_environment == CONDA_ENVIRONMENT:
        print(f"Conda environment: {CONDA_ENVIRONMENT}")
        return
    print(
        "WARNING: this script is configured for Conda environment "
        f"'{CONDA_ENVIRONMENT}', but the active environment is "
        f"'{active_environment or '<not detected>'}'."
    )
    print(
        f"Select the '{CONDA_ENVIRONMENT}' Python interpreter in VSCode or activate "
        "that Conda environment before running the full HDBSCAN analysis."
    )


def import_sklearn_components():
    try:
        from sklearn.cluster import HDBSCAN
        from sklearn.decomposition import PCA
        from sklearn.preprocessing import StandardScaler
    except ImportError as exc:
        raise RuntimeError(
            "scikit-learn with sklearn.cluster.HDBSCAN is required. "
            "Install scikit-learn >= 1.3 before running clustering."
        ) from exc
    return HDBSCAN, PCA, StandardScaler


def find_rule_label_column(columns: pd.Index) -> Optional[str]:
    by_lowercase = {column.lower(): column for column in columns}
    for candidate in RULE_LABEL_CANDIDATES:
        if candidate.lower() in by_lowercase:
            return by_lowercase[candidate.lower()]
    return None


def belongs_to_scenario(column: str, scenario: str) -> bool:
    """Keep generic indicators and current-scenario indicators only."""
    uppercase = column.upper()
    other_scenario = "TF" if scenario == "PF" else "PF"
    return other_scenario not in uppercase


def is_excluded_feature(column: str, id_columns: list[str]) -> bool:
    lowercase = column.lower()
    if column in id_columns:
        return True
    if lowercase in {candidate.lower() for candidate in RULE_LABEL_CANDIDATES}:
        return True
    return any(keyword in lowercase for keyword in EXCLUDED_FEATURE_KEYWORDS)


def select_features(
    data: pd.DataFrame, scenario: str, id_columns: list[str]
) -> tuple[list[str], list[str], list[str]]:
    scenario_columns = [
        column for column in data.columns if belongs_to_scenario(column, scenario)
    ]
    candidate_columns = [
        column
        for column in scenario_columns
        if not is_excluded_feature(column, id_columns)
    ]
    numeric_columns = set(data[candidate_columns].select_dtypes(include=[np.number]))
    non_numeric_columns = [
        column for column in candidate_columns if column not in numeric_columns
    ]
    numeric_candidates = [
        column for column in candidate_columns if column in numeric_columns
    ]
    constant_columns = [
        column for column in numeric_candidates if data[column].nunique(dropna=True) <= 1
    ]
    features = [
        column for column in numeric_candidates if column not in constant_columns
    ]
    return features, non_numeric_columns, constant_columns


def build_feature_summary(features: pd.DataFrame) -> pd.DataFrame:
    summary = features.agg(["min", "max", "mean", "std"]).transpose()
    summary["missing_value_count"] = features.isna().sum()
    summary.index.name = "feature"
    return summary.reset_index()


def save_list(path: Path, column_name: str, values: list[str]) -> None:
    pd.DataFrame({column_name: values}).to_csv(path, index=False)


def prepare_features(
    data: pd.DataFrame, scenario: str, output_dir: Path
) -> tuple[pd.DataFrame, Optional[str]]:
    id_columns = [column for column in ID_COLUMN_CANDIDATES if column in data.columns]
    rule_label_column = find_rule_label_column(data.columns)
    features, non_numeric_columns, constant_columns = select_features(
        data, scenario, id_columns
    )
    if not features:
        raise ValueError(f"No clustering features remain for scenario {scenario}.")

    feature_data = data[features].copy()
    summary = build_feature_summary(feature_data)
    summary.to_csv(output_dir / "feature_summary.csv", index=False)
    save_list(output_dir / "selected_features.csv", "feature", features)
    save_list(
        output_dir / "excluded_non_numeric_columns.csv",
        "excluded_non_numeric_column",
        non_numeric_columns,
    )
    save_list(
        output_dir / "excluded_constant_columns.csv",
        "excluded_constant_column",
        constant_columns,
    )

    extremes = summary[(summary["min"] < -1) | (summary["max"] > 1)].copy()
    extremes.to_csv(output_dir / "features_outside_minus1_to_1.csv", index=False)
    if extremes.empty:
        print("Extreme-value audit passed: selected features are within [-1, 1].")
    else:
        print("WARNING: selected features outside [-1, 1] were detected:")
        for row in extremes.itertuples(index=False):
            print(f"  - {row.feature}: min={row.min:g}, max={row.max:g}")

    missing_columns = summary[summary["missing_value_count"] > 0]
    if not missing_columns.empty:
        print("Missing values detected; median imputation will be applied:")
        for row in missing_columns.itertuples(index=False):
            print(f"  - {row.feature}: missing={row.missing_value_count}")
        feature_data = feature_data.fillna(feature_data.median())

    if feature_data.isna().any().any():
        raise ValueError("Missing feature values remain after median imputation.")

    print(f"Selected {len(features)} features for scenario {scenario}:")
    for feature in features:
        print(f"  - {feature}")
    if rule_label_column:
        print(f"Rule-based label detected for comparison: {rule_label_column}")
    else:
        print("No rule-based label column detected; comparison outputs will be skipped.")
    return feature_data, rule_label_column


def save_cluster_plot(
    coordinates: np.ndarray, labels: np.ndarray, output_path: Path, title: str
) -> None:
    plt.figure(figsize=(10, 8))
    plt.scatter(
        coordinates[:, 0],
        coordinates[:, 1],
        c=labels,
        cmap="tab20",
        s=3,
        alpha=0.65,
        rasterized=True,
    )
    plt.xlabel("PCA component 1")
    plt.ylabel("PCA component 2")
    plt.title(title)
    plt.colorbar(label="HDBSCAN cluster")
    plt.tight_layout()
    plt.savefig(output_path, dpi=200)
    plt.close()


def save_rule_label_plot(
    coordinates: np.ndarray,
    rule_labels: pd.Series,
    output_path: Path,
    title: str,
) -> None:
    codes, categories = pd.factorize(rule_labels.fillna("<missing>").astype(str))
    plt.figure(figsize=(10, 8))
    scatter = plt.scatter(
        coordinates[:, 0],
        coordinates[:, 1],
        c=codes,
        cmap="tab20",
        s=3,
        alpha=0.65,
        rasterized=True,
    )
    plt.xlabel("PCA component 1")
    plt.ylabel("PCA component 2")
    plt.title(title)
    colorbar = plt.colorbar(scatter, ticks=np.arange(len(categories)))
    colorbar.ax.set_yticklabels(categories)
    colorbar.set_label("Rule-based typology")
    plt.tight_layout()
    plt.savefig(output_path, dpi=200)
    plt.close()


def save_rule_comparison(
    clustered: pd.DataFrame, rule_label_column: str, run_dir: Path
) -> None:
    pd.crosstab(
        clustered[rule_label_column],
        clustered["hdbscan_cluster"],
        dropna=False,
    ).to_csv(run_dir / "rule_label_cluster_crosstab.csv")

    clustered_non_noise = clustered[clustered["hdbscan_cluster"] != -1].copy()
    majority_by_cluster = (
        clustered_non_noise.dropna(subset=[rule_label_column])
        .groupby("hdbscan_cluster")[rule_label_column]
        .agg(lambda values: values.value_counts().index[0])
    )
    clustered_non_noise["cluster_majority_rule_type"] = clustered_non_noise[
        "hdbscan_cluster"
    ].map(majority_by_cluster)
    conflicts = clustered_non_noise[
        clustered_non_noise[rule_label_column].notna()
        & clustered_non_noise["cluster_majority_rule_type"].notna()
        & (
            clustered_non_noise[rule_label_column]
            != clustered_non_noise["cluster_majority_rule_type"]
        )
    ]
    conflicts.to_csv(run_dir / "conflict_samples.csv", index=False)


def run_parameter_grid(
    data: pd.DataFrame,
    features: pd.DataFrame,
    rule_label_column: Optional[str],
    scenario: str,
    output_dir: Path,
) -> pd.DataFrame:
    HDBSCAN, PCA, StandardScaler = import_sklearn_components()
    versions = {
        "version_A_normalized": features.to_numpy(dtype=float),
        "version_B_standardized": StandardScaler().fit_transform(features),
    }
    summary_rows: list[dict[str, object]] = []

    for version_name, clustering_input in versions.items():
        version_dir = output_dir / version_name
        version_dir.mkdir(parents=True, exist_ok=True)
        coordinates = PCA(n_components=2).fit_transform(clustering_input)
        pd.DataFrame(
            coordinates, columns=["pca_component_1", "pca_component_2"]
        ).to_csv(version_dir / "pca_coordinates.csv", index=False)
        if rule_label_column:
            save_rule_label_plot(
                coordinates,
                data[rule_label_column],
                version_dir / "pca_rule_based_typology.png",
                f"{scenario} {version_name}: rule-based typology",
            )

        for min_cluster_size in MIN_CLUSTER_SIZES:
            for min_samples in MIN_SAMPLES_VALUES:
                run_name = (
                    f"min_cluster_size_{min_cluster_size}"
                    f"_min_samples_{min_samples}"
                )
                run_dir = version_dir / run_name
                run_dir.mkdir(parents=True, exist_ok=True)
                print(f"Running {scenario} {version_name} {run_name} ...")
                model = HDBSCAN(
                    min_cluster_size=min_cluster_size,
                    min_samples=min_samples,
                    metric=METRIC,
                    cluster_selection_method=CLUSTER_SELECTION_METHOD,
                )
                labels = model.fit_predict(clustering_input)
                clustered = data.copy()
                clustered["hdbscan_cluster"] = labels
                clustered.to_csv(run_dir / "clustered_street_segments.csv", index=False)

                cluster_sizes = (
                    pd.Series(labels, name="hdbscan_cluster")
                    .value_counts()
                    .rename_axis("hdbscan_cluster")
                    .reset_index(name="sample_count")
                    .sort_values("hdbscan_cluster")
                )
                cluster_sizes.to_csv(run_dir / "cluster_sizes.csv", index=False)
                non_noise_sizes = cluster_sizes[
                    cluster_sizes["hdbscan_cluster"] != -1
                ]["sample_count"]
                noise_count = int((labels == -1).sum())
                number_of_clusters = int(len(set(labels)) - (-1 in labels))
                noise_percentage = noise_count / len(labels) * 100
                largest_cluster_size = (
                    int(non_noise_sizes.max()) if not non_noise_sizes.empty else 0
                )

                pd.DataFrame(
                    [
                        {
                            "flood_scenario": scenario,
                            "version_name": version_name,
                            "min_cluster_size": min_cluster_size,
                            "min_samples": min_samples,
                            "metric": METRIC,
                            "cluster_selection_method": CLUSTER_SELECTION_METHOD,
                            "number_of_clusters": number_of_clusters,
                            "noise_count": noise_count,
                            "noise_percentage": noise_percentage,
                            "largest_cluster_size": largest_cluster_size,
                        }
                    ]
                ).to_csv(run_dir / "run_summary.csv", index=False)

                if rule_label_column:
                    save_rule_comparison(clustered, rule_label_column, run_dir)
                save_cluster_plot(
                    coordinates,
                    labels,
                    run_dir / "pca_hdbscan_clusters.png",
                    f"{scenario} {version_name}: HDBSCAN clusters",
                )
                summary_rows.append(
                    {
                        "flood_scenario": scenario,
                        "version_name": version_name,
                        "min_cluster_size": min_cluster_size,
                        "min_samples": min_samples,
                        "number_of_clusters": number_of_clusters,
                        "noise_count": noise_count,
                        "noise_percentage": noise_percentage,
                        "largest_cluster_size": largest_cluster_size,
                    }
                )
    return pd.DataFrame(summary_rows)


def print_reasonable_settings(summary: pd.DataFrame) -> None:
    reasonable = summary[
        (summary["number_of_clusters"] >= 2) & (summary["noise_percentage"] <= 50)
    ].sort_values(["noise_percentage", "number_of_clusters"], ascending=[True, False])
    if reasonable.empty:
        print("No parameter settings met the heuristic: >= 2 clusters and <= 50% noise.")
        return
    print("Reasonable parameter settings (heuristic: >= 2 clusters and <= 50% noise):")
    print(reasonable.head(5).to_string(index=False))


def main() -> None:
    args = parse_args()
    check_conda_environment()
    scenario = args.scenario.upper()
    input_path = args.input.resolve()
    output_dir = args.output_root.resolve() / scenario
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading: {input_path}")
    data = pd.read_csv(input_path)
    features, rule_label_column = prepare_features(data, scenario, output_dir)
    if args.audit_only:
        print("Audit-only mode completed; HDBSCAN was not run.")
        return

    summary = run_parameter_grid(
        data, features, rule_label_column, scenario, output_dir
    )
    summary.to_csv(output_dir / "hdbscan_parameter_summary.csv", index=False)
    print_reasonable_settings(summary)
    print(f"HDBSCAN outputs written to: {output_dir}")


if __name__ == "__main__":
    try:
        main()
    except (FileNotFoundError, RuntimeError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)
